### ISSUE TITLE
Intended use for multiple RUN commands

### ISSUE THREAD

**Issue by aleemb** [goldmann/docker-scripts#53] opened 2016-02-27 06:55 UTC
I have the following Dockerfiles:

```
# small
FROM ubuntu:14.04
RUN fallocate -l 100MB a.foo \
 && fallocate -l 150MB b.foo \
 && rm a.foo \
 && rm b.foo
```

```
# large
FROM ubuntu:14.04
RUN fallocate -l 100MB a.foo
RUN fallocate -l 150MB b.foo
RUN rm a.foo
RUN rm b.foo
```

I tried running `docker-squash -t squashed large` and but got errors regarding missing argument:

```
SquashError: Could not get the layer ID to squash, please check provided 'layer' argument: <missing>
```

I installed the `docker-v110` version.

**Comment by goldmann** [comment] 2016-02-27 08:10
Thanks for report. Two things:

1. docker-scripts does not support v1.10 yet
2. There is a WIP in the v2 branch to add support for v1.10. It's now in testing phase. If you use Docker 1.10 - use the v2 branch.

I'll close this as this a duplicate of #52. Please take a look at that issue for more information.

**Closed by goldmann** 2016-02-27 08:10 UTC
